[package]
name = "hacker-news-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json", "blocking"]}
serde = { version = "1.0.130", features = ["derive"]}
crossterm = "0.27.0"
